# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e91a885deb6c2d564b6947881faed2235c8759c3b04e12f8a3e28d9cc1006e861d85f43f9f73310d8f44926ff4976bc773228000b27693ee135bdbb8228b790

test:
  secret_key_base: 069b2a8fc3cd244129aa2577ae1940f66ccb77ed65f66c2821bd3553cb8a7f24d96021e41e937bb2cdfc76c76a69edd0916e06459d7bfb1b019caaa7ef5e08de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
